export interface MovieComponentData {
  title: string,
  character:string,
  overview: string,
  releaseDate:string,
  backdrop?:string,
  images?:string[],


}


const movies:any[] =[
  {title: "Breakin'", id: 15259, character: 'Spectator in First Dance Sequence', overview: 'A struggling young dancer joins forces with two br…cers and together they become a street sensation.', releaseDate: '1984-01-10'},
  {title: 'No Retreat, No Surrender', id: 12721, character: 'Ivan Kraschinsky "The Russian"', overview: 'Young Jason Stillwell moves with his parents to Se…rnational match against Ivan, a Russian champion.', releaseDate: '1986-05-02'},
  {title: 'Bloodsport', id: 11690, character: 'Frank Dux', overview: 'U.S. soldier Frank Dux has come to Hong Kong to be…ven the opportunity to fight. But can he survive?', releaseDate: '1988-02-26'},
  {title: 'Cyborg', id: 10134, character: 'Gibson Rickenbacker', overview: 'A martial artist hunts a killer in a plague-infested urban dump of the future.', releaseDate: '1989-04-07',backdrop:'inhell2.jpg', images:['inhell1.jpg','inhell2.jpg','inhell3.png','inhell4.jpg']},
  {title: 'Kickboxer', id: 10222, character: 'Kurt Sloane', overview: 'If your enemy refuses to be humbled... Destroy him…m for life. Crazed with anger, Kurt vows revenge.', releaseDate: '1989-04-20'},
  {title: 'Lionheart', id: 9399, character: 'Leon Gaultier', overview: 'Lyon Gaultier is a deserter in the Foreign Legion …e part in some very dangerous clandestine fights.', releaseDate: '1990-06-07'},
  {title: 'Death Warrant', id: 17466, character: 'Louis Burke', overview: 'The Canadian policeman Louis Burke is assigned in …ruggle of life and death tied in to his own past.', releaseDate: '1990-09-14'},
  {title: 'Double Impact', id: 9594, character: 'Alex / Chad Wagner', overview: 'Jean Claude Van Damme plays a dual role as Alex an…Chad, especially when it comes to his girlfriend.', releaseDate: '1991-07-31'},
  {title: 'Universal Soldier', id: 9349, character: 'Luc Deveraux / GR44', overview: 'An American soldier who had been killed during the…ashbacks that are forcing him to recall his past.', releaseDate: '1992-07-10'},
  {title: 'Nowhere to Run', id: 10413, character: 'Sam Gillen', overview: 'Escaped convict Sam Gillen single-handedly takes o…ermined to evict a widow with two young children.', releaseDate: '1993-01-15'},
  {title: 'Hard Target', id: 2019, character: 'Chance Boudreaux', overview: "When a woman's father goes missing, she enlists a …n who hunts homeless men as a form of recreation.", releaseDate: '1993-08-20'},
  {title: 'Timecop', id: 8831, character: 'Max Walker', overview: 'An officer for a security agency that regulates ti…nst a shady politician who has a tie to his past.', releaseDate: '1994-09-15'},
  {title: 'Street Fighter', id: 11667, character: 'Colonel William Guile', overview: 'Col. Guile and various other martial arts heroes f…the tyranny of Dictator M. Bison and his cohorts.', releaseDate: '1994-12-23'},
  {title: 'Sudden Death', id: 9091, character: 'Darren Francis Thomas McCord', overview: "When a man's daughter is suddenly taken during a c…t an impending explosion before the final buzzer.", releaseDate: '1995-10-27'},
  {title: 'The Quest', id: 9103, character: 'Christopher Dubois', overview: 'Ghang-gheng, the ancient winner-take-all competiti…ugh for Chris to triumph over such daunting foes.', releaseDate: '1996-04-19'},
  {title: 'Double Team', id: 9405, character: 'Jack Quinn', overview: 'A CIA agent is interned for failing to kill an int…al... with enough voltage to rock the free world.', releaseDate: '1997-04-04'},
  {title: 'Knock Off', id: 37498, character: 'Marcus Ray', overview: 'Marcus Ray, a sales representative for "V SIX" jea…a jail term if they do not prove their innocence.', releaseDate: '1998-09-04'},
  {title: 'Legionnaire', id: 3513, character: 'Alain Lefevre', overview: 'Alain Lefevre is a boxer paid by a Marseille mobst…with legionnaires Luther, Mackintosh and Rosetti.', releaseDate: '1998-12-03'},
  {title: 'Replicant', id: 10596, character: 'Replicant / Garrotte', overview: 'Scientists create a genetic clone of a serial kill… help catch the killer, teaming up with two cops.', releaseDate: '2001-05-11'},
  {title: 'In Hell', id: 19277, character: 'Kyle LeBlanc', overview: "A man must survive a prison where hardened crimina…ttle to the death for the warden's entertainment.", releaseDate: '2003-11-24'},
  {title: 'Second in Command', id: 19167, character: "Cmdr. Samuel 'Sam' Keenan", overview: "Armed insurgents attempt a coup d'etat in a troubl…ng martial arts technique to defend the besieged.", releaseDate: '2006-05-02'},
  {title: 'Until Death', id: 20411, character: 'Anthony Stowe', overview: 'Anthony Stowe is a dirty cop who is hooked on hero…it a better person who wants to put things right.', releaseDate: '2007-01-19'},
  {title: 'JCVD', id: 13672, character: 'J.C.V.D.', overview: 'Between his tax problems and his legal battle with…lity he can no longer enjoy in the United States.', releaseDate: '2008-06-04'},
  {title: 'Universal Soldier: Regeneration', id: 28510, character: 'Luc Deveraux', overview: 'When terrorists threaten nuclear catastrophe at Ch…eneration "UniSol" that seems almost unstoppable.', releaseDate: '2009-10-01'},
  {title: '6 Bullets', id: 127521, character: 'Samson Gaul', overview: 'An ex-mercenary known for finding missing children…l arts fighter whose daughter has been kidnapped.', releaseDate: '2012-09-11'},
  {title: 'Welcome to the Jungle', id: 205724, character: 'Storm', overview: 'A company retreat on a tropical island goes terribly awry.', releaseDate: '2013-04-27'},
  {title: 'Pound of Flesh', id: 326284, character: 'Deacon', overview: 'In China to donate his kidney to his dying niece, … for his niece and with each step he loses blood.', releaseDate: '2015-05-07'},
  {title: 'Kickboxer: Vengeance', id: 308529, character: 'Master Durand', overview: 'Eric and Kurt Sloane are the descendants of a well…arry him through his final showdown with Tong Po.', releaseDate: '2016-07-14'},
  {title: 'Kickboxer: Retaliation', id: 447665, character: 'Master Durand', overview: 'One year after the events of "Kickboxer: Vengeance…r to face Mongkut in hopes to regain his freedom.', releaseDate: '2018-01-26'},
  {title: 'The Bouncer', id: 525554, character: 'Lukas', overview: 'A tough nightclub bouncer struggling to raise his …rced to go undercover after an unfortunate event.', releaseDate: '2018-08-22'},
  {title: 'We Die Young', id: 538207, character: 'Daniel', overview: 'Lucas, a 14-year-old boy inducted into the gang li…mes into the neighborhood, an opportunity arises.', releaseDate: '2019-05-09'},
  // {title: 'Universal Soldier: The Return', id: 10366, character: 'Luc Devereux', overview: 'Luc Deveraux, the heroic former Universal Soldier,…t pits man against machine and good against evil.', releaseDate: '1999-08-05'},
  // {title: 'Maximum Risk', id: 10861, character: 'Alain Moreau / Mikhail Suverov', overview: "Alain Moreau's investigation into the death of his…'s murder and expose an international conspiracy.", releaseDate: '1996-09-13'},
  // {title: 'Inferno', id: 10908, character: 'Eddie Lomax', overview: 'Eddie Lomax (Jean-Claude Van Damme) is a drifter w…and several area ladies offering aid and comfort.', releaseDate: '1999-09-25'},
  // {title: 'The Shepherd: Border Patrol', id: 24411, character: 'Jack Robideaux', overview: 'A Texas cop battles ex-navy seals who are trying to traffic drugs from Mexico into the USA.', releaseDate: '2008-03-04'},
  // {title: 'The Hard Corps', id: 9924, character: 'Phillippe Sauvage', overview: 'An Army veteran assembles a team of bodyguards to … may be romantically involved with the bodyguard.', releaseDate: '2006-08-15'},
  // {title: 'Wake of Death', id: 14172, character: 'Ben Archer', overview: 'Ben Archer, an ex-mob enforcer, seeks revenge agai…n all-out war is waged against the Chinese Triad.', releaseDate: '2004-12-28'},
  // {title: 'The Order', id: 37632, character: 'Rudy Cafmeyer', overview: 'When Rudy, an artifacts smuggler, goes to Jerusale…ealots determined to see a holy war at all costs.', releaseDate: '2001-05-05'},
  // {title: 'Derailed', id: 17774, character: 'Jacques Kristoff', overview: 'NATO operative Jacques Kristoff (Jean-Claude Van D…sing as a couple, but soon all hell breaks loose.', releaseDate: '2002-05-19'},
  // {title: 'Frenchy', id: 51488, character: 'Frenchy', overview: 'Military veteran and former mercenary, FRENCHY wor…journey to save her he has the fight of his life.', releaseDate: '2010-05-13'},
  // {title: 'Assassination Games', id: 71677, character: 'Vincent Brazil', overview: 'Brazil is a contract killer, willing to take any j…eir target before they themselves are terminated.', releaseDate: '2011-07-28'},
  // {title: 'Dragon Eyes', id: 100683, character: 'Tiano', overview: 'In St. Jude, drug dealers and corrupt cops have de…s and moral vision to save this town from itself.', releaseDate: '2012-05-10'},
  // {title: 'Swelter', id: 256687, character: 'Stillman', overview: 'Ten years after their casino heist, four escaped c…now a lawman with no memory of his criminal past.', releaseDate: '2014-04-20'},
  // {title: 'Universal Soldier: Day of Reckoning', id: 122857, character: 'Luc Deveraux', overview: 'After his wife and daughter are murdered in a home…ises to set UniSols free from their conditioning.', releaseDate: '2012-10-04'},
  // {title: 'Enemies Closer', id: 238589, character: 'Xander', overview: 'After a major shipment of drugs goes missing on th…ill stop at nothing to retrieve their lost cargo.', releaseDate: '2013-12-04'},
  // {title: 'Dans la peau de Jean-Claude Van Damme', id: 317512, character: '', overview: 'If you want to find out how it is being Jean-Claude Van Damme.', releaseDate: '2003-05-07'},
  // {title: 'Barbarous Street', id: 76217, character: 'Extra in Police Arrival Sequence (uncredited)', overview: 'In this strange and beautiful crime drama, Bernard… the neighborhood will be different in the end...', releaseDate: '1984-01-04'},
  // {title: "Kill 'em All", id: 449503, character: 'Philip', overview: 'After a massive shootout, a mysterious stranger ar…cks a plot of international intrigue and revenge.', releaseDate: '2017-06-06'},
  // {title: 'Black Water', id: 454615, character: 'Wheeler', overview: 'A deep cover operative awakens to find himself imp…k to escape the vessel and expose who set him up.', releaseDate: '2018-05-18'},
  // {title: 'The Making of Double Impact, Parts 1 & 2', id: 619880, character: '', overview: 'Jean-Claude van Damme, Sheldon Lettich and more di…film "Double Impact" from inception to reception.', releaseDate: '2019-05-28'},
  // {title: 'Universal Soldier: A Tale of Two Titans', id: 684421, character: 'Himself', overview: 'Biography style segment that gives us some interes…onal archive photos and footage to tell its tale.', releaseDate: '2004-10-19'},
  // {title: "JCVD's Day Out", id: 687100, character: 'JCVD', overview: 'Action superstar Jean-Claude Van Damme tries to avoid spreading Covid-19 on his day out.', releaseDate: '2020-03-27'},
  // {title: 'The Last Mercenary', id: 729720, character: 'Richard Brumére', overview: "A legendary secret service agent comes out of hidi…o help the son he's never met get out of trouble.", releaseDate: '2021-07-30'},
  // {title: 'Monsieur Jean-Claude', id: 794863, character: '(uncredited)', overview: "Jean-Claude Van Damme is back, and this time it's …me of the images I watched repeatedly as a child.", releaseDate: '2021-07-15'},
  // {title: "What's My Name?", id: 941353, character: '', overview: '', releaseDate: ''},
  // {title: 'Black Eagle', id: 18214, character: 'Andrei', overview: "One of the US Air Force's most modern tactical air…s two young sons to a nearby hotel on the island.", releaseDate: '1988-05-01'},
  // {title: "Guns, Genes & Fighting Machines: The Making of 'Universal Soldier'", id: 684424, character: 'Himself', overview: 'Retrospective documentary on the making of the film Universal Soldier (1992).', releaseDate: '2004-10-19'},
  // {title: 'Ultimate Fights from the Movies', id: 68996, character: 'Max Walker (archive footage)', overview: "In their second film compilation following their '…Jackie Chan, Jean-Claude Van Damme and many more.", releaseDate: '2002-04-16'},
  // {title: 'Monaco Forever', id: 76172, character: 'Gay Karate Man', overview: 'An American jewel thief in Monaco encounters various characters while trying to set up a robbery.', releaseDate: '1984-01-01'},
  // {title: 'The Unbeatable Bruce Lee', id: 167688, character: 'Himself (archive footage)', overview: 'A look at the life of superstar Bruce Lee.', releaseDate: '2001-12-18'},
  // {title: 'U.F.O.', id: 146631, character: 'George', overview: 'A group of friends awake one morning to find all e…tened by the alien army hovering ominously above.', releaseDate: '2012-12-15'},
  // {title: 'Heist School', id: 27959, character: 'Charles', overview: 'Five high school students plans to steal University Entrance Exam booklets.', releaseDate: '2006-10-20'},
  // {title: 'The Go-Go Boys: The Inside Story of Cannon Films', id: 295099, character: 'Self', overview: 'Cousins Menahem Golan and Yoram Globus relive the … successes and discusses their eventual downfall.', releaseDate: '2014-10-22'},
  // {title: 'Corporal vs. Napoleon', id: 90804, character: 'Himself', overview: 'Napoleon has decided to declare war to the world. …him, so he will think about making love, not war.', releaseDate: '2012-01-25'},
  // {title: 'Woman Between Wolf and Dog', id: 198508, character: 'Movie Goer / Man in Garden (uncredited)', overview: 'Lieve is a Belgian woman who marries just as World…ve continued grief well after the end of the war.', releaseDate: '1979-06-04'},
  // {title: 'The Path of the Dragon', id: 167675, character: 'Himself (archive footage)', overview: "Produced and directed by Walt Missingham who, in 1… Narrated by Lee's daughter, Shannon Lee Keasler.", releaseDate: '1998-01-01'},
  // {title: 'The Expendables 2', id: 76163, character: 'Jean Vilain', overview: 'Mr. Church reunites the Expendables for what shoul…my territory and up against an unexpected threat.', releaseDate: '2012-08-08'},
  // {title: 'Top Fighter', id: 50151, character: 'Himself (Archive Footage)', overview: "Welcome to the world of the martial arts. A voyage…nt jewel of this genre what nobody wouldn't lose.", releaseDate: '1995-06-15'},
  // {title: 'Minions: The Rise of Gru', id: 438148, character: 'Jean Clawed (voice)', overview: 'A fanboy of a supervillain supergroup known as the…m, with the backup of his followers, the Minions.', releaseDate: '2022-06-29'},
  // {title: 'Beur sur la ville', id: 77460, character: 'Colonel Merot', overview: '25-year-old Khalid Belkacem has failed at everythi… for you! A country where everyone has a chance."', releaseDate: '2011-10-11'},
  // {title: 'All the Love You Cannes!', id: 99368, character: 'Self', overview: "Known for what must be the cheapest and cheesiest …reputation. And I think they're thinking, woohoo!", releaseDate: '2002-05-16'},
]
